vioinput: Fix build break with WDK 10.0.15063.0
The latest Win10 WDK added some more HID usage codes to hidusage.h
which broke the build.

  vioinput\sys\Hid.h(52): error C2220: warning treated as error - no 'object' file generated
  vioinput\sys\Hid.h(52): warning C4005: 'HID_USAGE_LED_SYSTEM_SUSPEND': macro redefinition
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared\hidusage.h(440): note: see previous definition of 'HID_USAGE_LED_SYSTEM_SUSPEND'

  vioinput\sys\Hid.h(59): warning C4005: 'HID_USAGE_DIGITIZER_STYLUS': macro redefinition
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared\hidusage.h(571): note: see previous definition of 'HID_USAGE_DIGITIZER_STYLUS'

  vioinput\sys\Hid.h(63): warning C4005: 'HID_USAGE_SIMULATION_BRAKE': macro redefinition
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared\hidusage.h(184): note: see previous definition of 'HID_USAGE_SIMULATION_BRAKE'

  vioinput\sys\Hid.h(64): warning C4005: 'HID_USAGE_SIMULATION_STEERING': macro redefinition
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared\hidusage.h(187): note: see previous definition of 'HID_USAGE_SIMULATION_STEERING'
  Build FAILED.

This commit fixes it by surrounding the affected macros with ifdefs.

Signed-off-by: Ladi Prosek <lprosek@redhat.com>